export default [
  {
    name: 'Campaign Manager Morty',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/61.jpeg',
    id: '61',
    type: '',
    species: 'Human',
    location: {
      name: 'Citadel of Ricks',
    },
  },
  {
    name: 'Canklanker Thom',
    status: 'unknown',
    image: 'https://rickandmortyapi.com/api/character/avatar/62.jpeg',
    id: '62',
    type: 'Gromflomite',
    species: 'Alien',
    location: {
      name: 'unknown',
    },
  },
  {
    name: 'Centaur',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/63.jpeg',
    id: '63',
    type: 'Centaur',
    species: 'Mythological Creature',
    location: {
      name: "Mr. Goldenfold's dream",
    },
  },
  {
    name: 'Chris',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/64.jpeg',
    id: '64',
    type: 'Organic gun',
    species: 'Alien',
    location: {
      name: 'Earth (Replacement Dimension)',
    },
  },
  {
    name: 'Chris',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/65.jpeg',
    id: '65',
    type: 'Microverse inhabitant',
    species: 'Humanoid',
    location: {
      name: "Rick's Battery Microverse",
    },
  },
  {
    name: 'Coach Feratu (Balik Alistane)',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/66.jpeg',
    id: '66',
    type: 'Vampire',
    species: 'Mythological Creature',
    location: {
      name: 'Earth (Replacement Dimension)',
    },
  },
  {
    name: 'Collector',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/67.jpeg',
    id: '67',
    type: 'Light bulb-Alien',
    species: 'Alien',
    location: {
      name: 'The Menagerie',
    },
  },
  {
    name: 'Colossus',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/68.jpeg',
    id: '68',
    type: '',
    species: 'Human',
    location: {
      name: 'Post-Apocalyptic Earth',
    },
  },
  {
    name: 'Commander Rick',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/69.jpeg',
    id: '69',
    type: '',
    species: 'Human',
    location: {
      name: 'Citadel of Ricks',
    },
  },
  {
    name: 'Concerto',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/70.jpeg',
    id: '70',
    type: '',
    species: 'Humanoid',
    location: {
      name: 'unknown',
    },
  },
  {
    name: 'Conroy',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/71.jpeg',
    id: '71',
    type: '',
    species: 'Robot',
    location: {
      name: 'Earth (C-137)',
    },
  },
  {
    name: 'Cool Rick',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/72.jpeg',
    id: '72',
    type: '',
    species: 'Human',
    location: {
      name: 'Citadel of Ricks',
    },
  },
  {
    name: 'Cop Morty',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/73.jpeg',
    id: '73',
    type: '',
    species: 'Human',
    location: {
      name: 'Citadel of Ricks',
    },
  },
  {
    name: 'Cop Rick',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/74.jpeg',
    id: '74',
    type: '',
    species: 'Human',
    location: {
      name: 'Citadel of Ricks',
    },
  },
  {
    name: 'Courier Flap',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/75.jpeg',
    id: '75',
    type: '',
    species: 'Alien',
    location: {
      name: 'Planet Squanch',
    },
  },
  {
    name: 'Cousin Nicky',
    status: 'Dead',
    image: 'https://rickandmortyapi.com/api/character/avatar/76.jpeg',
    id: '76',
    type: 'Parasite',
    species: 'Alien',
    location: {
      name: 'Earth (Replacement Dimension)',
    },
  },
  {
    name: 'Cowboy Morty',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/77.jpeg',
    id: '77',
    type: '',
    species: 'Human',
    location: {
      name: 'Citadel of Ricks',
    },
  },
  {
    name: 'Cowboy Rick',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/78.jpeg',
    id: '78',
    type: '',
    species: 'Human',
    location: {
      name: 'Citadel of Ricks',
    },
  },
  {
    name: 'Crab Spider',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/79.jpeg',
    id: '79',
    type: 'Animal',
    species: 'Alien',
    location: {
      name: 'Hideout Planet',
    },
  },
  {
    name: 'Creepy Little Girl',
    status: 'Alive',
    image: 'https://rickandmortyapi.com/api/character/avatar/80.jpeg',
    id: '80',
    type: '',
    species: 'Human',
    location: {
      name: "Mr. Goldenfold's dream",
    },
  },
];
